server:
  port: 8088
spring:
  application:
    name: client
  zipkin:
    base-url: http://localhost:8889
  mustache:
    suffix: .ftl
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
