server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhengzengjie/hello-world
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka